---
- name: Run Example Role
  hosts: all
  become: yes
  # If you need to run tasks with elevated privileges, set this to true
    

  tasks:
    - name: Update apt cache (for Debian/Ubuntu)
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Nginx
      apt:
        name: nginx
        state: present  # You can use "latest" here to make sure it's up-to-date
      when: ansible_os_family == 'Debian'

    - name: Install Nginx (for Red Hat/CentOS)
      yum:
        name: nginx
        state: present
      when: ansible_os_family == 'RedHat'

    - name: Start Nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy Nginx configuration
      template:
        src: nginx.conf.j2  # You need to create this Jinja2 template
        dest: /etc/nginx/nginx.conf
      notify:
        - Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded


 # roles:
  #  - name: mysql/ansible-role-mysql
